### PR TITLE
Backport fixes for proposal picker

### PR DESCRIPTION
**Pull request by phoebus-84**
#### :tophat: What? Why?
The filter in the admin picker for proposal did not work. Fix it width backporting from https://github.com/decidim/decidim/commit/6f5cc362c4ff09cdd2cb170ae0cbf5dca8398c67

#### :pushpin: Related Issues
- Related to #124
- Fixes #?

#### Testing
Test dont needed because it is a backport

#### :clipboard: Checklist
:rotating_light: Please review the [guidelines for contributing](https://github.com/decidim/decidim/blob/develop/CONTRIBUTING.adoc) to this repository.

- [x] :question: **CONSIDER** adding a unit test if your PR resolves an issue.
- [x] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [x] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [x] :heavy_check_mark: **DO** build locally before pushing.
- [x] :heavy_check_mark: **DO** make sure tests pass.
- [x] :heavy_check_mark: **DO** make sure any new changes are documented in `docs/`.
- [x] :heavy_check_mark: **DO** add and modify seeds if necessary.
- [x] :heavy_check_mark: **DO** add CHANGELOG upgrade notes if required.
- [x] :heavy_check_mark: **DO** add to GraphQL API if there are new public fields.
- [x] :heavy_check_mark: **DO** add link to MetaDecidim if it's a new feature.
- [x] :x:**AVOID** breaking the continuous integration build.
- [x] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots

:hearts: Thank you!

### CODE REVIEW

**Comment by microstudi** [comment]
Thanks @phoebus-84 , can you link the original PR in the decidim repostory please? thanks!

**Comment by phoebus-84** [comment]
> 

Sure but what do you mean exactly for original PR? These changes were backport from decidim/decidim:0.25-stable. Thanks!

**Comment by microstudi** [comment]
Yes, but a backport from a specific commit right? can you point me to it?

**Comment by phoebus-84** [comment]
> Yes, but a backport from a specific commit right? can you point me to it?

Thanks for the reply and there is it: https://github.com/decidim/decidim/commit/6f5cc362c4ff09cdd2cb170ae0cbf5dca8398c67

**Review by microstudi — COMMENTED** [review]
Thanks!
Before merging this, I see that the original commit had a javascript file affected as well. This file isn't relevant for the 0.24 version?

**Comment by phoebus-84** [comment]
> Thanks! Before merging this, I see that the original commit had a javascript file affected as well. This file isn't relevant for the 0.24 version?

That file was introduce here: https://github.com/decidim/decidim/commit/05b8ee799dfed85b17413531d6875509c8cd305c  So I think it is not relevant for 0.24.

**Comment by microstudi** [comment]
This file exists in the 0.24 version. When migrated to 0.25 and webpacker, all JS files where moved to the packs directory.
You can find this file in `decidim-proposals/app/assets/javascripts/decidim/proposals_picker.js.es6`

**Comment by microstudi** [comment]
Thanks @phoebus-84, merging!

**Pull request merged**
